# Example OpenAPI YAML to get you started quickly.
# Note: YAML has indentation based coping.
# Code completion support is available so start typing for
# available options.
# This example follows the recommendations of the API 
# Improvement Proposals for common API patterns. Find more
# at https://google.aip.dev/

# Find the full OpenAPI reference at:
# https://github.com/OAI/OpenAPI-Specification
openapi: "3.0.0"

info:
  version: "0.3.4-beta"
  title: Reasonable Adjustments API
  description: |
    ## Overview
    Use this API to access and update [Reasonable Adjustments (RA)](https://digital.nhs.uk/services/reasonable-adjustment-flag) - a new service which has been created to provide the means to access and update [Spine](https://digital.nhs.uk/services/spine) data relating to adjustments and impairments for patients with a learning disability or autism.  This API is a key enabler to NHS Digital’s requirement to adhere to one of the 9 digital milestones within the [NHS Long Term Plan](https://www.longtermplan.nhs.uk/online-version/chapter-3-further-progress-on-care-quality-and-outcomes/a-strong-start-in-life-for-children-and-young-people/learning-disability-and-autism/), which states: 

      **"By 2023/24, a ‘digital flag’ in the patient record will ensure staff know a patient has a learning disability or autism”.** 
  
      You can:
      - create a consent
      - create a flag
      - create a list
  
  
      - read a consent
      - read a flag
      - read a list
  
  
      - update a consent
      - update a flag
      - update a list
  
      - remove a RA record
  
      Currently, this API can only be accessed by healthcare professionals, authenticated with an NHS smartcard or equivalent.
    ## Legal Use
    This API can only be used where there is a legal basis to do so. Make sure you have a valid use case before you go too far with your development. 

    You must do this before you can go live (see ‘Onboarding’ below).
    
    ## Related APIs
    To use this API, you must also use one of the following APIs to retrieve a patient's demographic details before you can access their RA record:

      - [Personal Demographics Service (FHIR) API](https://portal.developer.nhs.uk/docs/personal-demographics-int/1/overview) - use this API to search for patients and retrieve their details.  This API can also be used to update their details in some cases. This is the latest version of the PDS API and is recommended for all new integrators.
      
     - [Personal Demographics Service (HL7 V3) API](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-hl7-v3) - use this API to search for patients and retrieve their details.  This API can also be used to update their details in some cases. Once our roadmap is complete, this API will become redundant, however you can continue to use this API as part of your RA development if you have an existing integration.
 
     When using this API, we also recommend that you consider using these related APIs:
 
      - [Female Genital Mutilation Information Sharing System (FGM-IS)](https://developer.nhs.uk/apis/fgm-v2.1/) - use this API to store and share FGM information of children under 18 with relevant NHS healthcare professionals across departments, organisations and geographical boundaries within England.
 
      - [Child Protection Information Sharing (CP-IS) - HL7 V3 API](https://digital.nhs.uk/services/child-protection-information-sharing-project/cp-is-domain-message-specification) - use this messaging and interactions guide to provide access to CP-IS, a sharing system which provides healthcare workers with access to recent unscheduled care attendance information for children under a local authority social care plan. 
 
      - [National Record Locator (NRL) (FHIR) API](https://developer.nhs.uk/apis/nrl/) - use this API to locate and share patient records held within local health and social care systems.
 
    ## API Status and Roadmap
    This API is in [beta](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#api-status), meaning:

      - we might make breaking changes, but only if we can't avoid it, and we'll give advance notice
      - we can't guarantee availability or performance
  
    The following items are on our roadmap:
      - basic analytics
      - implement status endpoints
      - implement proxy
      - implement rate limiting
        
      To see our roadmap, or to suggest, comment or vote on features for this API, see our [interactive product backlog](https://nhs-digital-api-management.featureupvote.com/suggestions/107521/reasonable-adjustments-ra-fhir-api).
  
      If you have any other queries, please [contact us](https://digital.nhs.uk/developer/help-and-support).
  
    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#basic-rest-apis). 

    It also conforms to the [FHIR (STU3)](https://www.hl7.org/fhir/STU3/) global standard for health care data exchange.

    You don’t need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules. In particular:
    - array names are singular, for example `line` not `lines` for address lines
    - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object


    ## Network Access
    This API is available on the Internet, but can be accessed with NHS smartcards through the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network) if necessary.  If you have a use case which requires access via HSCN please [contact us](https://digital.nhs.uk/developer/help-and-support).

    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and authorisation

    ### Authentication
    This API is [user-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis), meaning an end user must be present and authenticated to use it.

    The end user must be:
    - a healthcare professional
    - strongly authenticated, using either an NHS smartcard or a modern alternative

    ### Authorisation
    The API uses OAuth 2.0 to authorise the calling system. It supports the following security patterns:

      - user-restricted RESTful API - using NHS Identity - combined authentication and authorisation
      - user-restricted RESTful API - using NHS Identity - separate authentication and authorisation
 
     For more details, see [user-restricted APIs](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis).
 

    ## Environments and testing
    | Purpose           | URL                                                            |
    | -------------     | -----------------------------------------                      |
    | Sandbox           | `https://sandbox.service.nhs.uk/reasonable-adjustments`       |
    | Integration test (Available Nov 2020)  | `https://int.service.nhs.uk/reasonable-adjustments`           |
    | Production (Available Dec 2020/Jan 2021)         | `https://api.service.nhs.uk/reasonable-adjustments`  |


    ### Sandbox testing
    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):
      - is for early developer testing
      - only covers a limited set of scenarios
      - is stateless, so it does not actually persist any updates
      - is open access, so does not allow you to test authorisation
  
      For more details on sandbox testing, or to try out the sandbox using our \"Try this API\" feature, see the documentation for each endpoint.
  
    ### Integration testing
    Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):
      - is for formal integration testing
      - is stateful, so persists updates
      - includes authorisation with either a username/password or smartcard/PIN
  
      For more details see [integration testing with our RESTful APIs](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing-with-our-restful-apis).
  
    ## Resources
    For information on the resources used within the FHIR® Reasonable Adjustments API go to:

      [https://dev-reasonable-adjust-beta.netlify.app/explore.html](https://dev-reasonable-adjust-beta.netlify.app/explore.html)
  
    ## Onboarding
    You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it’s worth planning well ahead.

    To onboard for this API, follow the [Supplier Conformance Assessment List (SCAL) process.](https://digital.nhs.uk/developer/guides-and-documentation/onboarding-process#onboard-using-the-supplier-conformance-assessment-list-scal-process)
  
  contact:
    name: API Management Support
    email: api.management@nhs.net

servers:
  - url: 'https://sandbox.api.service.nhs.uk/reasonable-adjustments'
    description: Sandbox environment.

paths:
  /consent:
    post:
      summary: Create Consent
      description: Use this endpoint to create a consent, profiled as [RARecord-Consent-1](https://fhir.nhs.uk/STU3/StructureDefinition/RARecord-Consent-1), for a patient to record Reasonable Adjustment [Impairment](https://www.gov.uk/definition-of-disability-under-equality-act-2010) and [Adjustment](https://www.gov.uk/government/publications/reasonable-adjustments-a-legal-duty/reasonable-adjustments-a-legal-duty) information.
      operationId: postConsent
      parameters:
      - $ref: '#/components/parameters/patient'
      - $ref: '#/components/parameters/status'
      - $ref: '#/components/parameters/category'
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/RoleId'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      requestBody:
        description: Create consent
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: components/schemas/createConsent.yaml
            examples:
              success:
                value:
                  $ref: components/examples/createConsent.json           
      responses:
        '201':                                                      
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Date:
                    type: string
                    format: date-time
                    example: Tue, 23 Jul 2018 11:00:00 GMT
                  Last-Modified:
                    type: string
                    format: date-time
                    example: 2018-07-23T11:00:00+00:00
                  Location:
                    type: string
                    example: 
                  ETag:
                    type: string
                    example: resourceVID
                  Content-Type:
                    type: string
                    example: application/fhir+json
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/operationOutcome.yaml
              examples:
                invalid-nhsNumber:
                  summary: Invalid NHS Number for patient supplied.
                  value:
                    resourceType: OperationOutcome   
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1"
                              code: "INVALID_NHS_NUMBER"
                              display: "Invalid NHS number" 
      tags:
        - Endpoints              
                    
    get:
      summary: Read Consent
      description: Use this endpoint to read a consent, profiled as [RARecord-Consent-1](https://fhir.nhs.uk/STU3/StructureDefinition/RARecord-Consent-1), contained in a patient resource.
      operationId: readConsent
      parameters: 
      - $ref: '#/components/parameters/patient'
      - $ref: '#/components/parameters/status'
      - $ref: '#/components/parameters/category'
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/RoleId'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      responses:
        '200':                                                      
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Date:
                    type: string
                    format: date-time
                    example: Tue, 23 Jul 2018 11:00:00 GMT
                  Content-Type:
                    type: string
                    example: application/fhir+json
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/operationOutcome.yaml
              examples:
                invalid-nhsNumber:
                  summary: Invalid NHS Number for patient supplied.
                  value:
                    resourceType: OperationOutcome   
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1"
                              code: "INVALID_NHS_NUMBER"
                              display: "Invalid NHS number"                                
      tags:
        - Endpoints
  
  /consent/{consentID}:    
    put:
      summary: Update Consent
      description: Use this endpoint to update a consent, profiled as [RARecord-Consent-1](https://fhir.nhs.uk/STU3/StructureDefinition/RARecord-Consent-1), of a patient to update Reasonable Adjustment [Impairment](https://www.gov.uk/definition-of-disability-under-equality-act-2010) and [Adjustment](https://www.gov.uk/government/publications/reasonable-adjustments-a-legal-duty/reasonable-adjustments-a-legal-duty) information.
      operationId: updateConsent
      parameters:
      - $ref: '#/components/parameters/patient'
      - $ref: '#/components/parameters/status'
      - $ref: '#/components/parameters/category'
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/RoleId'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      - $ref: '#/components/parameters/consentID' 
      requestBody:
        description: Update record
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: components/schemas/updateFlag.yaml
            examples:
              success:
                value:
                  $ref: components/examples/updateFlag.json     
      responses:
        '200':                                                      
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Date:
                    type: string
                    format: date-time
                    example: Tue, 23 Jul 2018 11:00:00 GMT
                  Last-Modified:
                    type: string
                    format: date-time
                    example: 2018-07-23T11:00:00+00:00
                  ETag:
                    type: string
                    example: resourceVID
                  Content-Type:
                    type: string
                    example: application/fhir+json
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/operationOutcome.yaml
              examples:
                invalid-nhsNumber:
                  summary: Invalid NHS Number for patient supplied.
                  value:
                    resourceType: OperationOutcome   
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1"
                              code: "INVALID_NHS_NUMBER"
                              display: "Invalid NHS number"                 
      tags:
        - Endpoints    
        
  /flag:
    post:
      summary: Create Flag
      description: Use this endpoint to create a flag, profiled as [RARecord-Flag-1](https://fhir.nhs.uk/STU3/StructureDefinition/RARecord-Flag-1/_history/0.0.5), for a patient.  This can then be used to record specific [Adjustments - as defined under the Equality Act (2010)](https://www.gov.uk/government/publications/reasonable-adjustments-a-legal-duty/reasonable-adjustments-a-legal-duty), which have been identified by the patient or supporting healthcare professional.
      operationId: postFlag
      parameters:
      - $ref: '#/components/parameters/patient'
      - $ref: '#/components/parameters/status'
      - $ref: '#/components/parameters/category'
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/RoleId'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      requestBody:
        description: Create flag
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: components/schemas/createFlag.yaml
            examples:
              success:
                value:
                  $ref: components/examples/createFlag.json 
              
      responses:
        '201':                                                      
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Date:
                    type: string
                    format: date-time
                    example: Tue, 23 Jul 2018 11:00:00 GMT
                  Last-Modified:
                    type: string
                    format: date-time
                    example: 2018-07-23T11:00:00+00:00
                  Location:
                    type: string
                    example: 
                  ETag:
                    type: string
                    example: resourceVID
                  Content-Type:
                    type: string
                    example: application/fhir+json
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/operationOutcome.yaml
              examples:
                invalid-nhsNumber:
                  summary: Invalid NHS Number for patient supplied.
                  value:
                    resourceType: OperationOutcome   
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1"
                              code: "INVALID_NHS_NUMBER"
                              display: "Invalid NHS number" 
      tags:
        - Endpoints              
                    
    get:
      summary: Read Flag
      description: Use this endpoint to read a flag, profiled as [RARecord-Flag-1](https://fhir.nhs.uk/STU3/StructureDefinition/RARecord-Flag-1/_history/0.0.5), contained in a patient resource.
      operationId: readFlag
      parameters: 
      - $ref: '#/components/parameters/patient'
      - $ref: '#/components/parameters/status'
      - $ref: '#/components/parameters/category'
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/RoleId'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      responses:
        '200':                                                      
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Date:
                    type: string
                    format: date-time
                    example: Tue, 23 Jul 2018 11:00:00 GMT
                  Content-Type:
                    type: string
                    example: application/fhir+json
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/operationOutcome.yaml
              examples:
                invalid-nhsNumber:
                  summary: Invalid NHS Number for patient supplied.
                  value:
                    resourceType: OperationOutcome   
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1"
                              code: "INVALID_NHS_NUMBER"
                              display: "Invalid NHS number"                
      tags:
        - Endpoints
  
  /flag/{flagID}:    
    put:
      summary: Update Flag
      description: Use this endpoint to update a flag, profiled as [RARecord-Flag-1](https://fhir.nhs.uk/STU3/StructureDefinition/RARecord-Flag-1/_history/0.0.5), for a patient to update specific [Adjustments - as defined under the Equality Act (2010)](https://www.gov.uk/government/publications/reasonable-adjustments-a-legal-duty/reasonable-adjustments-a-legal-duty), which have been identified by the patient or supporting healthcare professional.
      operationId: updateFlag
      parameters:
      - $ref: '#/components/parameters/patient'
      - $ref: '#/components/parameters/status'
      - $ref: '#/components/parameters/category'
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/RoleId'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      - $ref: '#/components/parameters/If-Match'
      - $ref: '#/components/parameters/flagID'
      requestBody:
        description: Update flag
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: components/schemas/updateFlag.yaml
            examples:
              success:
                value:
                  $ref: components/examples/updateFlag.json        
      responses:
        '200':                                                      
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Date:
                    type: string
                    format: date-time
                    example: Tue, 23 Jul 2018 11:00:00 GMT
                  Last-Modified:
                    type: string
                    format: date-time
                    example: 2018-07-23T11:00:00+00:00
                  ETag:
                    type: string
                    example: resourceVID
                  Content-Type:
                    type: string
                    example: application/fhir+json
        '409':
          description: CONFLICT
          content:
            application/json:
              schema:
                type: object
                properties:
                  Date:
                    type: string
                    format: date-time
                    example: Tue, 23 Jul 2018 11:00:00 GMT
                  Content-Type:
                    type: string
                    example: application/fhir+json
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/operationOutcome.yaml
              examples:
                invalid-nhsNumber:
                  summary: Invalid NHS Number for patient supplied.
                  value:
                    resourceType: OperationOutcome   
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1"
                              code: "INVALID_NHS_NUMBER"
                              display: "Invalid NHS number"            
      tags:
        - Endpoints 
  
  /list:
    post:
      summary: Create List
      description: Use this endpoint to create a list, profiled as [CareConnect-RARecord-List-1](https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-RARecord-List-1), for storing a new Impairment resource.
      operationId: postList
      parameters:
      - $ref: '#/components/parameters/patient'
      - $ref: '#/components/parameters/status'
      - $ref: '#/components/parameters/code'
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/RoleId'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      requestBody:
        description: Create list
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: components/schemas/createList.yaml
            examples:
              success:
                value:
                  $ref: components/examples/createList.json 
              
      responses:
        '201':                                                      
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Date:
                    type: string
                    format: date-time
                    example: Tue, 23 Jul 2018 11:00:00 GMT
                  Last-Modified:
                    type: string
                    format: date-time
                    example: 2018-07-23T11:00:00+00:00
                  Location:
                    type: string
                    example: 
                  ETag:
                    type: string
                    example: resourceVID
                  Content-Type:
                    type: string
                    example: application/fhir+json
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/operationOutcome.yaml
              examples:
                invalid-nhsNumber:
                  summary: Invalid NHS Number for patient supplied.
                  value:
                    resourceType: OperationOutcome   
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1"
                              code: "INVALID_NHS_NUMBER"
                              display: "Invalid NHS number" 
      tags:
        - Endpoints              
                    
    get:
      summary: Read List
      description: Use this endpoint to read a list, profiled as [CareConnect-RARecord-List-1](https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-RARecord-List-1), of a patient’s impairment resources.
      operationId: readList
      parameters: 
      - $ref: '#/components/parameters/patient'
      - $ref: '#/components/parameters/status'
      - $ref: '#/components/parameters/code'
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/RoleId'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      responses:
        '200':                                                      
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Date:
                    type: string
                    format: date-time
                    example: Tue, 23 Jul 2018 11:00:00 GMT
                  Content-Type:
                    type: string
                    example: application/fhir+json
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/operationOutcome.yaml
              examples:
                invalid-nhsNumber:
                  summary: Invalid NHS Number for patient supplied.
                  value:
                    resourceType: OperationOutcome   
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1"
                              code: "INVALID_NHS_NUMBER"
                              display: "Invalid NHS number"                 
      tags:
        - Endpoints
  
  /list/{listID}:    
    put:
      summary: Update List
      description: Use this endpoint to remove entries in a list, profiled as [CareConnect-RARecord-List-1](https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-RARecord-List-1), of a patient, by changing the delete value of an entry to true.
      operationId: updateList
      requestBody:
        description: Update list
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: components/schemas/updateList.yaml
            examples:
              success:
                value:
                  $ref: components/examples/updateList.json 
      parameters: 
      - $ref: '#/components/parameters/patient'
      - $ref: '#/components/parameters/status'
      - $ref: '#/components/parameters/code'
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/RoleId'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      - $ref: '#/components/parameters/If-Match'
      - $ref: '#/components/parameters/listID'
      responses:
        '200':                                                      
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Date:
                    type: string
                    format: date-time
                    example: Tue, 23 Jul 2018 11:00:00 GMT
                  Last-Modified:
                    type: string
                    format: date-time
                    example: 2018-07-23T11:00:00+00:00
                  ETag:
                    type: string
                    example: resourceVID
                  Content-Type:
                    type: string
                    example: application/fhir+json
        '409':
          description: CONFLICT
          content:
            application/json:
              schema:
                type: object
                properties:
                  Date:
                    type: string
                    format: date-time
                    example: Tue, 23 Jul 2018 11:00:00 GMT
                  Content-Type:
                    type: string
                    example: application/fhir+json  
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/operationOutcome.yaml
              examples:
                invalid-nhsNumber:
                  summary: Invalid NHS Number for patient supplied.
                  value:
                    resourceType: OperationOutcome   
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1"
                              code: "INVALID_NHS_NUMBER"
                              display: "Invalid NHS number" 
      tags:
        - Endpoints
        
  /removerarecord:
    post:
      summary: Remove RA Record
      description: Use this endpoint to remove an RA record by providing a removal reason, profiled as [CodeSystem-RARecord-RemovalReason-1](https://fhir.nhs.uk/STU3/CodeSystem/CodeSystem-RARecord-RemovalReason-1). This triggers the system to inactivate all RA resources contained in a patient resource.
      operationId: removeRecord
      requestBody:
        description: Remove RA record
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: components/schemas/removerarecord.yaml
            examples:
              success:
                value:
                  $ref: components/examples/removerarecord.json                    
      parameters:
      - $ref: '#/components/parameters/patient'
      - $ref: '#/components/parameters/removalReason'
      - $ref: '#/components/parameters/supportingComment'
      - $ref: '#/components/parameters/BearerAuthorization'
      - $ref: '#/components/parameters/RoleId'
      - $ref: '#/components/parameters/CorrelationID'
      - $ref: '#/components/parameters/RequestID'
      responses:
        '200':                                                      
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Date:
                    type: string
                    format: date-time
                    example: Tue, 23 Jul 2018 11:00:00 GMT
                  Content-Type:
                    type: string
                    example: application/fhir+json
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/fhir+json:
                schema:
                  $ref: components/schemas/operationOutcome.yaml
                examples:
                  invalid-nhsNumber:
                    summary: Invalid NHS Number for patient supplied.
                    value:
                      resourceType: OperationOutcome   
                      issue:
                        - severity: error
                          code: value
                          details:
                            coding:
                              - system: "https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1"
                                code: "INVALID_NHS_NUMBER"
                                display: "Invalid NHS number" 
      tags:
        - Endpoints    

components:
  parameters:
    nhsNumber:
      name: nhsNumber
      in: query
      required: true
      description: ID number of a patient
      schema:
        type: object
        properties:
          name:
            type: string
            example: "nhsNumber"
          valueString:
            type: string
            example: "999999998"
    removalReason:
      name: removalReason
      in: query
      required: true
      description: Code recording Removal Reason
      schema:
        type: object
        properties:
          name:
            type: string
            example: "removalReason"
          valueCodeableConcept:
            type: object
            properties:
              coding:
                type: array
                items:
                  type: object
                  properties:
                    system:
                      type: string
                      example: "https://fhir.nhs.uk/STU3/CodeSystem/CodeSystem-RARecord-RemovalReason-1"
                    code:
                      type: string
                      example: "DoesntApply"
                    display:
                      type: string
                      example: "The Reasonable Adjustment Flag no longer applies to the patient"
    supportingComment:
      name: supportingComment
      in: query
      required: true
      description: Comment supporting Removal Reason
      schema:
        type: object
        properties:
          name:
            type: string
            example: "supportingComment"
          valueString:
            type: string
            example: "No longer applies"    
    If-Match:
      name: If-Match
      in: header
      required: true
      description: Latest known version identifier enclosed in quotes preceded by `W/`.
      schema:
        type: string
        example: "aa755bd6-2be9-4971-972a-6724879c5cb1"
    consentID:
      name: consentID
      in: path
      required: true
      description: The id of the record
      schema:
        type: string
        example: "1"
    flagID:
      name: flagID
      in: path
      required: true
      description: The id of the flag
      schema:
        type: string
        example: "1"
    listID:
      name: listID
      in: path
      required: true
      description: The id of the list
      schema:
        type: string
        example: "1"    
    patient:
      name: patient
      in: query
      required: true
      description: The id of the patient
      schema:
        type: string
        example: "9999999998"    
    status:
      name: status
      in: query
      required: true
      description: status
      schema:
        type: string
        example: "active" 
    category:
      name: category
      in: query
      required: true
      description: category
      schema:
        type: string
        example: "https://fhir.nhs.uk/STU3/CodeSystem/CodeSystem-RARecord-FlagCategory-1|reasonable%20adjustments%20flag&_format=json"
    code:
      name: code
      in: query
      required: true
      description: code
      schema:
        type: string
        example: "http://snomed.info/sct|1094391000000102&_format=json"
    RoleId:
      name: NHSD-Session-URID
      in: header
      required: false
      description: |
        A User Role ID (URID), also known as a User Role Profile ID (URPID), specifies the role the user is acting in.
        A URID belongs to a user (they are not generic) and a user may have more than one.
        Find out more about [User role ID](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-identity-combined-authentication-and-authorisation#step-6-determine-the-user-s-role)
        
        **Note: This parameter is required unless interacting with the Sandbox.**
      schema:
        type: string
        pattern: '^[0-9]+$'
        example: '555021935107'
    BearerAuthorization:
      name: Authorization
      in: header
      required: false
      description: |
        An [OAuth 2.0 bearer token](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis).
        
        **Note: This parameter is required unless interacting with the Sandbox.**
      schema:
        type: string
        pattern: '^Bearer\ [[:ascii:]]+$'
        example: 'Bearer g1112R_ccQ1Ebbb4gtHBP1aaaNM'
    CorrelationID:
      name: X-Correlation-ID
      in: header
      required: false
      description: |
        An identifer should be created when making a request, this will assist with any problems that may occur and should be included when an issue is raised with the helpdesk.
        It should ideally be a unique value to make message tracing easier and we would advise that there are no `"."` characters, but these are not enforced.
        This will be mirrored back in the response headers.
      schema:
        type: string
        example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
    RequestID:
      name: X-Request-ID
      in: header
      required: false
      description: |
        A **globally unique identifer (GUID)** should be created when making a request, this will be used in message de-duplication, meaning if you need to replay any messages an identical response will be returned as the first time.
        The identifer must be a universally unique identifier (UUID) (ideally version 4).
        This will be mirrored back in the response headers.
        
        **Note: This parameter is required for `update`, `get` and `search` unless interacting with the Sandbox.**
      schema:
        type: string
        pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
        example: 60E0B220-8136-4CA5-AE46-1D97EF59D068
tags:
- name: Reasonable Adjustments 